default_language_version:
  # force all unspecified python hooks to run python3
  python: python3.9
minimum_pre_commit_version: '2.20.0'
files: src
repos:
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
        exclude: '\/migrations\/'
        args: ['--py36-plus']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: double-quote-string-fixer
        exclude: '\/migrations\/'
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
        types: [python]
      - id: mixed-line-ending
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ['--py3-plus', '--py39-plus']

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.12.0"  # replace with latest tag on GitHub
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.1"]   # Replace with Django version
  # linters
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.20.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.12.6
          - flake8-no-pep420==2.3.0
          - flake8-encodings==0.5.0
